title: Pedro Marinho
description: >
  Blog técnico sobre programação, backend, Linux e desenvolvimento fullstack.
lang: pt-BR
author:
  name: Pedro Marinho
  email: pedroermarinho@gmail.com

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


minima:
  skin: solarized-light
  show_excerpts: true
  date_format: "%d/%m/%Y"
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/pedroermarinho"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/pedroermarinho"
    - title: YouTube
      icon: youtube
      url: "https://youtube.com/@pedroermarinho"

permalink: /:categories/:year/:month/:day/:title.html
