title: Pedro Marinho - Blog
description: Um blog técnico sobre programação, backend, linux e desenvolvimento fullstack.

author:
  name: Pedro Marinho
  email: pedroermarinho@gmail.com

theme: minima 

minima:
  social_links:
    github: pedroermarinho
    linkedin: pedroermarinho
  date_format: "%d/%m/%Y"

permalink: /:categories/:year/:month/:day/:title.html
